[tool.poetry]
name = "ninja"
version = "0.1.0"
description = ""
authors = ["subhamivan <ivan.sarangi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "4.2.5"
channels = "4.0.0"
daphne = "4.0.0"
channels-redis = "^4.2.0"
django-ninja = "^1.3.0"
python-dotenv = "^1.0.1"
psycopg2-binary = "^2.9.9"
mongoengine = "^0.29.1"
pymongo = "^4.10.1"
uvicorn = "^0.32.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
