# Generated by Django 4.2.5 on 2024-10-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_group_chat',
            field=models.BooleanField(default=False),
        ),
    ]
